### ISSUE TITLE
released xcframeworks doesn't contain macOS version

### ISSUE THREAD

**Issue by cuhte3** [lightningdevkit/ldk-swift#24]
First of all thanks for the awesome library! 

I've added universal xcframework from release page into my iOS/MacOS app but Xcode fails to build macOS target with the message: 

`
While building for macOS, no library for this platform was found in '/User/lightningDevKit/LDK-Universal-Test/Frameworks/LDKFramework.xcframework'
`

If you inspect LDKFramework.xcframework there are only iOS versions

- ios-arm64 
- ios-x86_64-maccatalyst
- ios-x86_64-simulator

Missed versions are (?)

- macos-arm64  
- macos-x86_64

LDKFramework-only-macOS.xcframework has only iOS version as well

-  ios-x86_64-maccatalyst

Am trying to build macOS version from scratch following the updated readme but currently stuck on generation swift files step:

`
ldk-swift % EXPORT LDK_SWIFT_GENERATOR_INPUT_HEADER_PATH="/User/lightningDevKit/ldk-c-bindings/lightning-c-bindings/include/lightning.h"
python3 ./
zsh: command not found: EXPORT
Cleaning up bindings/LDK directory: /User/lightningDevKit/ldk-swift/bindings/LDK
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 4, in <module>
    generate_sdk()
  File "./src/sdk_generator.py", line 110, in generate_sdk
    parser = parse_header()
  File "./src/sdk_generator.py", line 17, in parse_header
    header_file = LightningHeaderParser.get_file()
  File "./src/lightning_header_parser.py", line 61, in get_file
    with open(header_path, 'r', encoding='utf-8') as lightning_header_handle:
FileNotFoundError: [Errno 2] No such file or directory: './src/../input/lightning.h'
`

**Comment by arik-so** [comment]
I'm happy to take input and suggestions regarding how to modify `compile_dependency_binaries.sh` to add support for default non-Catalyst Mac targets :)

**Comment by cuhte3** [comment]
@arik-so I'd added additional directory for catalyst 
```
FRAMEWORK_PROJECT_DIRECTORY_CATALYST="`pwd`/LDKFramework_Catalyst"
```
and build four targets for macOS

**Catalyst arm64**

```
cargo build -Z build-std=panic_abort,std --features "std" --target aarch64-apple-ios-macabi --release
cp "${C_BINDINGS_SOURCE_DIRECTORY}/target/aarch64-apple-ios-macabi/release/libldk.a" $FRAMEWORK_PROJECT_DIRECTORY_CATALYST
```

**Catalyst x86_64**

```
cargo build -Z build-std=panic_abort,std --features "std" --target x86_64-apple-ios-macabi --release
cp "${C_BINDINGS_SOURCE_DIRECTORY}/target/x86_64-apple-ios-macabi/release/libldk.a" $FRAMEWORK_PROJECT_DIRECTORY_CATALYST
```

**MacOS arm64**

```
cargo build -Z build-std=panic_abort,std --features "std" --target aarch64-apple-darwin --release
cp "${C_BINDINGS_SOURCE_DIRECTORY}/target/aarch64-apple-darwin/release/libldk.a" $FRAMEWORK_PROJECT_DIRECTORY_MAC
```

**MacOS x86_64**

```
cargo build -Z build-std=panic_abort,std --features "std" --target x86_64-apple-darwin --release
cp "${C_BINDINGS_SOURCE_DIRECTORY}/target/x86_64-apple-darwin/release/libldk.a" $FRAMEWORK_PROJECT_DIRECTORY_MAC

```

Additionally resulting libs could be merged into arm64 + x86_64 binaries

**Catalyst**

`lipo "${C_BINDINGS_SOURCE_DIRECTORY}/target/aarch64-apple-ios-macabi/release/libldk.a"  "${C_BINDINGS_SOURCE_DIRECTORY}/target/x86_64-apple-ios-macabi/release/libldk.a"  -create -output libldk.a`

**macOS**

`lipo "${C_BINDINGS_SOURCE_DIRECTORY}/target/aarch64-apple-darwin/release/libldk.a"  "${C_BINDINGS_SOURCE_DIRECTORY}/target/x86_64-apple-darwin/release/libldk.a"  -create -output libldk.a`

The macOS + iOS/iOS simulator binaries will cover most of apple platforms (unless we don't need ldk for Apple TV and Apple Watch)

**Comment by arik-so** [comment]
Thank you so much! I think admittedly the idea of running Lightning from an Apple TV is perhaps a bit ambitious, but who am I to say no. I'll try running your build script modifications on my machine later today.

**Comment by cuhte3** [comment]
I was able to build static libs for all those architectures a while ago. Final step is to build the universal xcframeworks. The Xcode projects in the repo (LDKFramework/LDKFramework_Mac) are missing module map and plist files and doesn't build in Xcode :/ When I run `build_framework.sh` script I've got the error:

While archiving I've got the error: 

```
** ARCHIVE FAILED **


The following build commands failed:
	Ld /Users/cuhte3/Library/Developer/Xcode/DerivedData/LDKFramework-fneuplswncykdybwopycmpvqifjs/Build/Intermediates.noindex/ArchiveIntermediates/LDKFramework/InstallationBuildProductsLocation/Library/Frameworks/LDKFramework.framework/Versions/A/LDKFramework normal (in target 'LDKFramework' from project 'LDKFramework')
(1 failure)
```

Am using M1 mac

Any suggestions @arik-so

**Comment by jurvis** [comment]
@cuhte3 can you post a full gist of the build error? 

also if you could post an output of `nm /path/to/LDKFramework.xframework/LDKFramework` and `lipo -info /path/to/LDKFramework.xframework/LDKFramework` that will be useful 😄

**Comment by cuhte3** [comment]
So here is more info of the build error @jurvis:

```
CompileC /Users/cuhte3/Library/Developer/Xcode/DerivedData/LDKFramework-fneuplswncykdybwopycmpvqifjs/Build/Intermediates.noindex/ArchiveIntermediates/LDKFramework/IntermediateBuildFilesPath/LDKFramework.build/Release-maccatalyst/LDKFramework.build/Objects-normal/x86_64/LDKFramework_vers.o /Users/cuhte3/Library/Developer/Xcode/DerivedData/LDKFramework-fneuplswncykdybwopycmpvqifjs/Build/Intermediates.noindex/ArchiveIntermediates/LDKFramework/IntermediateBuildFilesPath/LDKFramework.build/Release-maccatalyst/LDKFramework.build/DerivedSources/LDKFramework_vers.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler (in target 'LDKFramework' from project 'LDKFramework')
    cd /Users/cuhte3/Dev/lightningDevKit/ldk-swift/xcode/LDKFramework_Mac
    export LANG\=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c -target x86_64-apple-ios13.1-macabi -fmessage-length\=110 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -fcolor-diagnostics -std\=gnu11 -fmodules -gmodules -fmodules-cache-path\=/Users/cuhte3/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/cuhte3/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -fmodule-name\=LDKFramework -Wno-trigraphs -fpascal-strings -Os -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Wquoted-include-in-framework-header -Werror\=deprecated-objc-isa-usage -Werror\=objc-root-class -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -Wunguarded-availability -iquote /Users/cuhte3/Library/Developer/Xcode/DerivedData/LDKFramework-fneuplswncykdybwopycmpvqifjs/Build/Intermediates.noindex/ArchiveIntermediates/LDKFramework/IntermediateBuildFilesPath/LDKFramework.build/Release-maccatalyst/LDKFramework.build/LDKFramework-generated-files.hmap -I/Users/cuhte3/Library/Developer/Xcode/DerivedData/LDKFramework-fneuplswncykdybwopycmpvqifjs/Build/Intermediates.noindex/ArchiveIntermediates/LDKFramework/IntermediateBuildFilesPath/LDKFramework.build/Release-maccatalyst/LDKFramework.build/LDKFramework-own-target-headers.hmap -I/Users/cuhte3/Library/Developer/Xcode/DerivedData/LDKFramework-fneuplswncykdybwopycmpvqifjs/Build/Intermediates.noindex/ArchiveIntermediates/LDKFramework/IntermediateBuildFilesPath/LDKFramework.build/Release-maccatalyst/LDKFramework.build/LDKFramework-all-non-framework-target-headers.hmap -ivfsoverlay /Users/cuhte3/Library/Developer/Xcode/DerivedData/LDKFramework-fneuplswncykdybwopycmpvqifjs/Build/Intermediates.noindex/ArchiveIntermediates/LDKFramework/IntermediateBuildFilesPath/LDKFramework.build/Release-maccatalyst/LDKFramework.build/all-product-headers.yaml -iquote /Users/cuhte3/Library/Developer/Xcode/DerivedData/LDKFramework-fneuplswncykdybwopycmpvqifjs/Build/Intermediates.noindex/ArchiveIntermediates/LDKFramework/IntermediateBuildFilesPath/LDKFramework.build/Release-maccatalyst/LDKFramework.build/LDKFramework-project-headers.hmap -I/Users/cuhte3/Library/Developer/Xcode/DerivedData/LDKFramework-fneuplswncykdybwopycmpvqifjs/Build/Intermediates.noindex/ArchiveIntermediates/LDKFramework/BuildProductsPath/Release-maccatalyst/include -I/Users/cuhte3/Dev/lightningDevKit/ldk-swift/xcode/LDKFramework_Mac -isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/System/iOSSupport/usr/include -I/Users/cuhte3/Library/Developer/Xcode/DerivedData/LDKFramework-fneuplswncykdybwopycmpvqifjs/Build/Intermediates.noindex/ArchiveIntermediates/LDKFramework/IntermediateBuildFilesPath/LDKFramework.build/Release-maccatalyst/LDKFramework.build/DerivedSources-normal/x86_64 -I/Users/cuhte3/Library/Developer/Xcode/DerivedData/LDKFramework-fneuplswncykdybwopycmpvqifjs/Build/Intermediates.noindex/ArchiveIntermediates/LDKFramework/IntermediateBuildFilesPath/LDKFramework.build/Release-maccatalyst/LDKFramework.build/DerivedSources/x86_64 -I/Users/cuhte3/Library/Developer/Xcode/DerivedData/LDKFramework-fneuplswncykdybwopycmpvqifjs/Build/Intermediates.noindex/ArchiveIntermediates/LDKFramework/IntermediateBuildFilesPath/LDKFramework.build/Release-maccatalyst/LDKFramework.build/DerivedSources -F/Users/cuhte3/Library/Developer/Xcode/DerivedData/LDKFramework-fneuplswncykdybwopycmpvqifjs/Build/Intermediates.noindex/ArchiveIntermediates/LDKFramework/BuildProductsPath/Release-maccatalyst -iframework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/System/iOSSupport/System/Library/Frameworks -MMD -MT dependencies -MF /Users/cuhte3/Library/Developer/Xcode/DerivedData/LDKFramework-fneuplswncykdybwopycmpvqifjs/Build/Intermediates.noindex/ArchiveIntermediates/LDKFramework/IntermediateBuildFilesPath/LDKFramework.build/Release-maccatalyst/LDKFramework.build/Objects-normal/x86_64/LDKFramework_vers.d --serialize-diagnostics /Users/cuhte3/Library/Developer/Xcode/DerivedData/LDKFramework-fneuplswncykdybwopycmpvqifjs/Build/Intermediates.noindex/ArchiveIntermediates/LDKFramework/IntermediateBuildFilesPath/LDKFramework.build/Release-maccatalyst/LDKFramework.build/Objects-normal/x86_64/LDKFramework_vers.dia -c /Users/cuhte3/Library/Developer/Xcode/DerivedData/LDKFramework-fneuplswncykdybwopycmpvqifjs/Build/Intermediates.noindex/ArchiveIntermediates/LDKFramework/IntermediateBuildFilesPath/LDKFramework.build/Release-maccatalyst/LDKFramework.build/DerivedSources/LDKFramework_vers.c -o /Users/cuhte3/Library/Developer/Xcode/DerivedData/LDKFramework-fneuplswncykdybwopycmpvqifjs/Build/Intermediates.noindex/ArchiveIntermediates/LDKFramework/IntermediateBuildFilesPath/LDKFramework.build/Release-maccatalyst/LDKFramework.build/Objects-normal/x86_64/LDKFramework_vers.o

Ld /Users/cuhte3/Library/Developer/Xcode/DerivedData/LDKFramework-fneuplswncykdybwopycmpvqifjs/Build/Intermediates.noindex/ArchiveIntermediates/LDKFramework/InstallationBuildProductsLocation/Library/Frameworks/LDKFramework.framework/Versions/A/LDKFramework normal (in target 'LDKFramework' from project 'LDKFramework')
    cd /Users/cuhte3/Dev/lightningDevKit/ldk-swift/xcode/LDKFramework_Mac
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-ios13.1-macabi -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk -L/Users/cuhte3/Library/Developer/Xcode/DerivedData/LDKFramework-fneuplswncykdybwopycmpvqifjs/Build/Intermediates.noindex/ArchiveIntermediates/LDKFramework/BuildProductsPath/Release-maccatalyst -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/System/iOSSupport/usr/lib -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/maccatalyst -L/Users/cuhte3/Dev/lightningDevKit/ldk-swift/xcode/LDKFramework_Mac -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/System/iOSSupport/usr/lib -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/maccatalyst -F/Users/cuhte3/Library/Developer/Xcode/DerivedData/LDKFramework-fneuplswncykdybwopycmpvqifjs/Build/Intermediates.noindex/ArchiveIntermediates/LDKFramework/BuildProductsPath/Release-maccatalyst -iframework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/System/iOSSupport/System/Library/Frameworks -iframework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/System/iOSSupport/System/Library/Frameworks -filelist /Users/cuhte3/Library/Developer/Xcode/DerivedData/LDKFramework-fneuplswncykdybwopycmpvqifjs/Build/Intermediates.noindex/ArchiveIntermediates/LDKFramework/IntermediateBuildFilesPath/LDKFramework.build/Release-maccatalyst/LDKFramework.build/Objects-normal/x86_64/LDKFramework.LinkFileList -install_name @rpath/LDKFramework.framework/Versions/A/LDKFramework -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -object_path_lto -Xlinker /Users/cuhte3/Library/Developer/Xcode/DerivedData/LDKFramework-fneuplswncykdybwopycmpvqifjs/Build/Intermediates.noindex/ArchiveIntermediates/LDKFramework/IntermediateBuildFilesPath/LDKFramework.build/Release-maccatalyst/LDKFramework.build/Objects-normal/x86_64/LDKFramework_lto.o -Xlinker -final_output -Xlinker /Library/Frameworks/LDKFramework.framework/Versions/A/LDKFramework -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx -L/System/iOSSupport/usr/lib/swift -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/cuhte3/Library/Developer/Xcode/DerivedData/LDKFramework-fneuplswncykdybwopycmpvqifjs/Build/Intermediates.noindex/ArchiveIntermediates/LDKFramework/IntermediateBuildFilesPath/LDKFramework.build/Release-maccatalyst/LDKFramework.build/Objects-normal/x86_64/LDKFramework.swiftmodule -lldk -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/cuhte3/Library/Developer/Xcode/DerivedData/LDKFramework-fneuplswncykdybwopycmpvqifjs/Build/Intermediates.noindex/ArchiveIntermediates/LDKFramework/IntermediateBuildFilesPath/LDKFramework.build/Release-maccatalyst/LDKFramework.build/Objects-normal/x86_64/LDKFramework_dependency_info.dat -o /Users/cuhte3/Library/Developer/Xcode/DerivedData/LDKFramework-fneuplswncykdybwopycmpvqifjs/Build/Intermediates.noindex/ArchiveIntermediates/LDKFramework/InstallationBuildProductsLocation/Library/Frameworks/LDKFramework.framework/Versions/A/LDKFramework
ld: warning: Could not find or use auto-linked library 'libldk.a'
Undefined symbols for architecture x86_64:
  "_CResult_InvoiceNoneZ_clone", referenced from:
      LDKFramework.Result_InvoiceNoneZ.clone() -> LDKFramework.Result_InvoiceNoneZ in Result_InvoiceNoneZ.o
  "_CResult_InvoiceNoneZ_err", referenced from:
      static LDKFramework.Result_InvoiceNoneZ.err() -> LDKFramework.Result_InvoiceNoneZ in Result_InvoiceNoneZ.o
  "_CResult_InvoiceNoneZ_free", referenced from:
      LDKFramework.Result_InvoiceNoneZ.deinit in Result_InvoiceNoneZ.o
  "_CResult_InvoiceNoneZ_is_ok", referenced from:
      static LDKFramework.Bindings.swift_CResult_InvoiceNoneZ_is_ok(o: LDKFramework.Result_InvoiceNoneZ) -> Swift.Bool in Bindings.o
     (maybe you meant: dispatch thunk of static LDKFramework.Bindings.swift_CResult_InvoiceNoneZ_is_ok(o: LDKFramework.Result_InvoiceNoneZ) -> Swift.Bool, static LDKFramework.Bindings.swift_CResult_InvoiceNoneZ_is_ok(o: LDKFramework.Result_InvoiceNoneZ) -> Swift.Bool , method descriptor for static LDKFramework.Bindings.swift_CResult_InvoiceNoneZ_is_ok(o: LDKFramework.Result_InvoiceNoneZ) -> Swift.Bool )
  "_CResult_InvoiceNoneZ_ok", referenced from:
      static LDKFramework.Result_InvoiceNoneZ.ok(o: LDKFramework.Invoice) -> LDKFramework.Result_InvoiceNoneZ in Result_InvoiceNoneZ.o
  "_CResult_ProbabilisticScoringParametersDecodeErrorZ_clone", referenced from:
      LDKFramework.Result_ProbabilisticScoringParametersDecodeErrorZ.clone() -> LDKFramework.Result_ProbabilisticScoringParametersDecodeErrorZ in Result_ProbabilisticScoringParametersDecodeErrorZ.o
  "_CResult_ProbabilisticScoringParametersDecodeErrorZ_err", referenced from:
      static LDKFramework.Result_ProbabilisticScoringParametersDecodeErrorZ.err(e: LDKFramework.DecodeError) -> LDKFramework.Result_ProbabilisticScoringParametersDecodeErrorZ in Result_ProbabilisticScoringParametersDecodeErrorZ.o
  "_CResult_ProbabilisticScoringParametersDecodeErrorZ_free", referenced from:
      LDKFramework.Result_ProbabilisticScoringParametersDecodeErrorZ.deinit in Result_ProbabilisticScoringParametersDecodeErrorZ.o
  "_CResult_ProbabilisticScoringParametersDecodeErrorZ_is_ok", referenced from:
      static LDKFramework.Bindings.swift_CResult_ProbabilisticScoringParametersDecodeErrorZ_is_ok(o: LDKFramework.Result_ProbabilisticScoringParametersDecodeErrorZ) -> Swift.Bool in Bindings.o
     (maybe you meant: method descriptor for static LDKFramework.Bindings.swift_CResult_ProbabilisticScoringParametersDecodeErrorZ_is_ok(o: LDKFramework.Result_ProbabilisticScoringParametersDecodeErrorZ) -> Swift.Bool, static LDKFramework.Bindings.swift_CResult_ProbabilisticScoringParametersDecodeErrorZ_is_ok(o: LDKFramework.Result_ProbabilisticScoringParametersDecodeErrorZ) -> Swift.Bool , dispatch thunk of static LDKFramework.Bindings.swift_CResult_ProbabilisticScoringParametersDecodeErrorZ_is_ok(o: LDKFramework.Result_ProbabilisticScoringParametersDecodeErrorZ) -> Swift.Bool )
  "_CResult_ProbabilisticScoringParametersDecodeErrorZ_ok", referenced from:
      static LDKFramework.Result_ProbabilisticScoringParametersDecodeErrorZ.ok(o: LDKFramework.ProbabilisticScoringParameters) -> LDKFramework.Result_ProbabilisticScoringParametersDecodeErrorZ in Result_ProbabilisticScoringParametersDecodeErrorZ.o
  "_CResult_SiPrefixNoneZ_clone", referenced from:
      LDKFramework.Result_SiPrefixNoneZ.clone() -> LDKFramework.Result_SiPrefixNoneZ in Result_SiPrefixNoneZ.o
  "_CResult_SiPrefixNoneZ_err", referenced from:
      static LDKFramework.Result_SiPrefixNoneZ.err() -> LDKFramework.Result_SiPrefixNoneZ in Result_SiPrefixNoneZ.o
  "_CResult_SiPrefixNoneZ_free", referenced from:
      LDKFramework.Result_SiPrefixNoneZ.deinit in Result_SiPrefixNoneZ.o
  "_CResult_SiPrefixNoneZ_is_ok", referenced from:
      static LDKFramework.Bindings.swift_CResult_SiPrefixNoneZ_is_ok(o: LDKFramework.Result_SiPrefixNoneZ) -> Swift.Bool in Bindings.o
     (maybe you meant: dispatch thunk of static LDKFramework.Bindings.swift_CResult_SiPrefixNoneZ_is_ok(o: LDKFramework.Result_SiPrefixNoneZ) -> Swift.Bool, method descriptor for static LDKFramework.Bindings.swift_CResult_SiPrefixNoneZ_is_ok(o: LDKFramework.Result_SiPrefixNoneZ) -> Swift.Bool , static LDKFramework.Bindings.swift_CResult_SiPrefixNoneZ_is_ok(o: LDKFramework.Result_SiPrefixNoneZ) -> Swift.Bool )
  "_CResult_SiPrefixNoneZ_ok", referenced from:
      static LDKFramework.Result_SiPrefixNoneZ.ok(o: __C.LDKSiPrefix) -> LDKFramework.Result_SiPrefixNoneZ in Result_SiPrefixNoneZ.o
  "_CResult_SignedRawInvoiceNoneZ_clone", referenced from:
      LDKFramework.Result_SignedRawInvoiceNoneZ.clone() -> LDKFramework.Result_SignedRawInvoiceNoneZ in Result_SignedRawInvoiceNoneZ.o
  "_CResult_SignedRawInvoiceNoneZ_err", referenced from:
      static LDKFramework.Result_SignedRawInvoiceNoneZ.err() -> LDKFramework.Result_SignedRawInvoiceNoneZ in Result_SignedRawInvoiceNoneZ.o
  "_CResult_SignedRawInvoiceNoneZ_free", referenced from:
      LDKFramework.Result_SignedRawInvoiceNoneZ.deinit in Result_SignedRawInvoiceNoneZ.o
  "_CResult_SignedRawInvoiceNoneZ_is_ok", referenced from:
      static LDKFramework.Bindings.swift_CResult_SignedRawInvoiceNoneZ_is_ok(o: LDKFramework.Result_SignedRawInvoiceNoneZ) -> Swift.Bool in Bindings.o
     (maybe you meant: method descriptor for static LDKFramework.Bindings.swift_CResult_SignedRawInvoiceNoneZ_is_ok(o: LDKFramework.Result_SignedRawInvoiceNoneZ) -> Swift.Bool, dispatch thunk of static LDKFramework.Bindings.swift_CResult_SignedRawInvoiceNoneZ_is_ok(o: LDKFramework.Result_SignedRawInvoiceNoneZ) -> Swift.Bool , static LDKFramework.Bindings.swift_CResult_SignedRawInvoiceNoneZ_is_ok(o: LDKFramework.Result_SignedRawInvoiceNoneZ) -> Swift.Bool )
  "_CResult_SignedRawInvoiceNoneZ_ok", referenced from:
      static LDKFramework.Result_SignedRawInvoiceNoneZ.ok(o: LDKFramework.SignedRawInvoice) -> LDKFramework.Result_SignedRawInvoiceNoneZ in Result_SignedRawInvoiceNoneZ.o
  "_ProbabilisticScoringParameters_read", referenced from:
      static LDKFramework.ProbabilisticScoringParameters.read(ser: [Swift.UInt8]) -> LDKFramework.Result_ProbabilisticScoringParametersDecodeErrorZ in ProbabilisticScoringParameters.o
  "_ProbabilisticScoringParameters_write", referenced from:
      LDKFramework.ProbabilisticScoringParameters.write() -> [Swift.UInt8] in ProbabilisticScoringParameters.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** ARCHIVE FAILED **


The following build commands failed:
	Ld /Users/cuhte3/Library/Developer/Xcode/DerivedData/LDKFramework-fneuplswncykdybwopycmpvqifjs/Build/Intermediates.noindex/ArchiveIntermediates/LDKFramework/InstallationBuildProductsLocation/Library/Frameworks/LDKFramework.framework/Versions/A/LDKFramework normal (in target 'LDKFramework' from project 'LDKFramework')
```

As far as I can see there is a warning  `Could not find or use auto-linked library 'libldk.a'`, also a list of `Undefined symbols for architecture x86_64`. I guess the host Xcode project isn't properly configured on my end

**Comment by jurvis** [comment]
@cuhte3 thanks, this is helpful. I don't really have any solutions for you at the current moment, but I'll loop you in once I get the PR up with the new tooling to make sure it works for your use-case!

**Comment by cuhte3** [comment]
I've just notice the xcframework also missing an iOS arm64 simulator lib = doesn't run in iOS simulator on m1 Macs

**Comment by arik-so** [comment]
Sorry, I'm finally able to get around to this. I would like to point out that on my non-M1-Mac running the latest Big Sur with the latest Xcode, I get architecture unsupported errors when trying to build the binaries for `aarch64-apple-ios-macabi` and `aarch64-apple-darwin`, whereas both `x86_64-…` architectures seem to work just fine.

**Comment by arik-so** [comment]
Additionally, I see that you're suggesting merging the arm64 and x86 binaries separately. Is there any drawback to lipoing all the binaries into one big libldk.a which would hopefully get optimized out for App Store deployments, and which would allow only having one directory instead of LDKFramework, LDKFramework_Mac, and LDKFramework_Catalyst?

**Comment by cuhte3** [comment]
> Sorry, I'm finally able to get around to this. I would like to point out that on my non-M1-Mac running the latest Big Sur with the latest Xcode, I get architecture unsupported errors when trying to build the binaries for `aarch64-apple-ios-macabi` and `aarch64-apple-darwin`, whereas both `x86_64-…` architectures seem to work just fine.

@arik-so  probably you need to install additional instructions set. you can see all the supported targets by running `rustup target list` on your machine. however according to [the list](https://doc.rust-lang.org/nightly/rustc/platform-support.html) `aarch64-apple-ios-macabi` is in tier 3 means there is no official build. catalyst not a deal breaker for me personally :)

**Comment by arik-so** [comment]
Hm, it doesn't appear to be a rust toolchain issue, that's the first thing I checked. But I'll keep looking, thanks!

**Comment by cuhte3** [comment]
last week I was able to build static libs for all the targets listed above on my m1 mac running Monterey. let me know if I can be helpful here, thanks!

**Comment by jurvis** [comment]
@cuhte3 I just put up #43, which includes a [change](https://github.com/lightningdevkit/ldk-swift/pull/43/commits/67e91f9c092038cd08b308b511576f924edff0df) to support building non-catalyst, darwin-based framework builds :) 

I'm working on getting CI up to get some sanity checks now. Catalyst is last on my list.

**Comment by cuhte3** [comment]
@jurvis you made my day! <3

**Comment by jurvis** [comment]
@cuhte3 oh and additional cherry on top: #43 will also add iOS simulator support for arm64 macs :)

Your SwiftUI previews should work again
